title: Ravi Prakash Meghwanshi
logo: /images/Picture.jpg

description: |
  🎓 PhD Researcher in Haptic Perception & Psychophysics
  <br><br>
  📧 [Email: meghwanshi.1@iitj.ac.in](mailto:meghwanshi.1@iitj.ac.in)<br>
  🎓 <a href="https://scholar.google.com/citations?user=8wTCmckAAAAJ&hl=en&authuser=1">Google Scholar</a><br>
  💼 <a href="https://linkedin.com/in/rpmeghwanshi">LinkedIn</a>

theme: jekyll-theme-minimal
